spring:
  datasource:
    url: ${DB_URL}
    username: username
    password: password
    driver-class-name: org.postgresql.Driver

  application:
    name: booknetwork

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOSTNAME}
    port: 465
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 626B5970337336763979244226452948404D635166546A576E5A723475377821
      expiration: 86400000

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account/

  cors:
    origin: http://localhost:4200,http://localhost:8081,http://localhost:8088,http://13.48.58.134:8088,http://13.48.58.134:8081

  file:
    upload:
      photos-output-path: ./uploads
server:
  port: 8088
