spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    driver-class-name: org.postgresql.Driver
    username: username
    password: password

  application:
    name: booknetwork

  #jpa:
    #hibernate:
      #ddl-auto: create-drop
    #database-platform: org.hibernate.dialect.H2Dialect

  mail:
    host: smtp.gmail.com
    username: abdussalaamabdulafeez@gmail.com
    password: dlginyczgzdvysov
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 626B5970337336763979244226452948404D635166546A576E5A723475377821
      expiration: 86400000

  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account/

  cors:
    origins: http://localhost:4200,http://localhost:8081,http://localhost:8088,http://13.48.58.134:8088,http://13.48.58.134:8081

  file:
    upload:
      photos-output-path: ./uploads

server:
  port: 8088
